// Capability Catalog — plain-English documentation of every backend router
// discovered in energyplanner0613. Static, in-shell reference only. No
// fetch, no env, no auth. Seed/demo data only.

import type { CapabilityGroup, CapabilityStatus, UiStatus } from "./capabilities";
import { CAPABILITIES } from "./capabilities";

export type CatalogEntry = {
  id: string;                  // matches CAPABILITIES[].id
  title: string;               // human title
  what: string;                // what it does
  why: string;                 // why it exists
  who: string;                 // who uses it
  homeownerQuestion: string;   // homeowner-facing question it answers
  inputs: string[];            // demo inputs
  outputs: string[];           // demo outputs
  related: string[];           // other capability ids
  recommendedSection: CapabilityGroup;
  sampleInput?: Record<string, unknown>;
  sampleOutput?: Record<string, unknown>;
};

// All values are seed/demo only — illustrative, not from a real home.
export const CATALOG: CatalogEntry[] = [
  // ─── Home ────────────────────────────────────────────────────────────
  {
    id: "accounts",
    title: "Accounts & session",
    what: "Owns the homeowner identity, the active session, and which homes that identity can see.",
    why: "Everything else in the system is scoped to 'whose home is this?'. Without an account there is no twin to draw.",
    who: "Every signed-in homeowner; contractors who get scoped read access; admins managing access.",
    homeownerQuestion: "Is this my home, and am I signed in to see it?",
    inputs: ["Email or OAuth token", "Home id the user is asking about"],
    outputs: ["User id", "Display initials", "List of home ids this user can open"],
    related: ["homes", "privacy", "crm_handoff"],
    recommendedSection: "home",
    sampleInput: { email: "demo@example.com" },
    sampleOutput: { userId: "u_demo", initials: "DG", homes: ["h_demo"] },
  },
  {
    id: "homes",
    title: "Homes",
    what: "The root record for a property: address, owner, year built, square footage.",
    why: "Anchors every other capability — panel, loads, scenarios, evidence — to one physical address.",
    who: "Homeowners viewing their twin; contractors reading the shared home.",
    homeownerQuestion: "What does the system know about my house at a glance?",
    inputs: ["Home id"],
    outputs: ["Street address", "Year built", "Square footage", "Owner display name"],
    related: ["accounts", "buildings", "facts"],
    recommendedSection: "home",
    sampleInput: { homeId: "h_demo" },
    sampleOutput: { address: "123 Demo Lane", yearBuilt: 1978, sqft: 1850 },
  },
  {
    id: "buildings",
    title: "Building envelope",
    what: "Physical building attributes: walls, insulation class, roof type, orientation, window count.",
    why: "These shape every energy estimate — a leaky 1950s envelope and a tight 2015 build need different pathways.",
    who: "Planner uses it to size HVAC; Explore uses it to explain why a recommendation makes sense.",
    homeownerQuestion: "How efficient is the shell of my house today?",
    inputs: ["Home id"],
    outputs: ["Envelope grade", "Roof type", "Window count", "Orientation"],
    related: ["homes", "facts", "energy_passport"],
    recommendedSection: "home",
    sampleOutput: { envelope: "B-", roof: "asphalt shingle", windows: 14 },
  },
  {
    id: "panels",
    title: "Electrical panel",
    what: "The main service panel: amperage, busbar rating, breaker positions, free slots.",
    why: "Almost every electrification choice depends on whether the panel can take another load.",
    who: "Planner (capacity check), Builder (what the contractor will work on), Inspector drawer.",
    homeownerQuestion: "Does my panel have room for what I want to add?",
    inputs: ["Home id"],
    outputs: ["Service size (amps)", "Free breaker slots", "Manufacturer", "Age"],
    related: ["loads", "nec_load_calculation", "system_visibility"],
    recommendedSection: "home",
    sampleOutput: { service: 100, freeSlots: 3, brand: "Square D" },
  },
  {
    id: "loads",
    title: "Loads & circuits",
    what: "Inventory of major loads (HVAC, water heater, range, EV) and which breakers serve them.",
    why: "Drives backup planning, panel sizing, and the 'what will keep running in an outage' card.",
    who: "Homeowner in Backup Loads view; Planner deciding what a battery has to carry.",
    homeownerQuestion: "Which appliances stay on if the grid goes down?",
    inputs: ["Home id"],
    outputs: ["Circuit list", "Estimated peak load", "Backup-eligible flag per circuit"],
    related: ["panels", "energy_passport", "nec_load_calculation"],
    recommendedSection: "home",
    sampleOutput: { circuits: 18, peakKw: 9.4, backupEligible: 6 },
  },
  {
    id: "energy_passport",
    title: "Energy passport",
    what: "A summary card: annual kWh, peak kW, fuel mix, current carbon intensity.",
    why: "Gives the homeowner one number they can hold onto before any planning happens.",
    who: "Homeowner on the twin; Planner as a baseline; Builder for context.",
    homeownerQuestion: "What does my home use in a year, and how dirty is it?",
    inputs: ["Home id", "Optional 12 months of utility readings"],
    outputs: ["Annual kWh", "Annual therms", "Peak kW", "CO2e/year"],
    related: ["buildings", "loads", "twin_planning_context"],
    recommendedSection: "home",
    sampleOutput: { annualKwh: 11800, peakKw: 6.1, co2eKg: 4200 },
  },
  {
    id: "system_visibility",
    title: "System visibility",
    what: "Per-system status: Known, Needs info, or Not added — drives the colored dots everywhere.",
    why: "Lets the UI honestly distinguish 'we know this' from 'we are guessing' without hiding either.",
    who: "Every surface that shows a status dot — twin, planner, inspector.",
    homeownerQuestion: "What does the system actually know vs. assume about my home?",
    inputs: ["Home id"],
    outputs: ["Map of system → {status, confidence, last seen}"],
    related: ["evidence", "provenance", "facts"],
    recommendedSection: "home",
    sampleOutput: { panel: "known", solar: "not_added", battery: "needs_info" },
  },
  {
    id: "nec_load_calculation",
    title: "NEC load calculation",
    what: "Runs the National Electrical Code load calc to size service and confirm a panel can support new equipment.",
    why: "Required before any meaningful electrification advice — it is the gating math.",
    who: "Planner (capacity gating), Builder (permit-ready output), advanced homeowners.",
    homeownerQuestion: "Can I add an EV charger and a heat pump without a service upgrade?",
    inputs: ["Panel record", "Existing loads", "Proposed new loads"],
    outputs: ["Calculated demand (amps)", "Headroom remaining", "Service upgrade required y/n"],
    related: ["panels", "loads", "scenarios"],
    recommendedSection: "home",
    sampleOutput: { calculatedAmps: 92, headroomAmps: 8, upgradeRequired: true },
  },

  // ─── Explore ─────────────────────────────────────────────────────────
  {
    id: "product_preferences",
    title: "Goals & priorities",
    what: "What the homeowner says they care about: cost, resilience, carbon, brand loyalty, time horizon.",
    why: "Two homes with identical hardware can want very different pathways. This biases the recommender honestly.",
    who: "Homeowner editing goals; Planner ranking pathways; Design advisor.",
    homeownerQuestion: "What matters most to me in this decision?",
    inputs: ["Sliders / chips: resilience, cost, carbon, comfort"],
    outputs: ["Weighted priority vector used by the recommender"],
    related: ["design_advisor", "scenarios", "twin_planning_context"],
    recommendedSection: "explore",
    sampleOutput: { resilience: 0.6, cost: 0.3, carbon: 0.1 },
  },
  {
    id: "product_library",
    title: "Product library",
    what: "Catalog of inverters, batteries, panels, heat pumps with specs and ecosystem tags.",
    why: "Real comparisons need a shared spec sheet, not vendor marketing.",
    who: "Planner (Compare ecosystems); Builder (BOM); Compatibility engine.",
    homeownerQuestion: "What can I actually buy, and how do the options stack up?",
    inputs: ["Filters: ecosystem, kW range, certifications"],
    outputs: ["Product list with normalized specs"],
    related: ["proposal_option_sets", "compatibility_rules", "equipment"],
    recommendedSection: "explore",
    sampleOutput: { results: 24, ecosystems: ["Tesla", "Enphase", "FranklinWH"] },
  },
  {
    id: "source_documents",
    title: "Source documents",
    what: "Citable references behind every Learn card: utility tariffs, code excerpts, manufacturer datasheets.",
    why: "Trust requires receipts. Learn must point to the document, not just paraphrase it.",
    who: "Explore Learn cards; Inspector provenance basis.",
    homeownerQuestion: "Where did this claim come from, and can I read it myself?",
    inputs: ["Topic id or capability id"],
    outputs: ["Document title", "Publisher", "URL", "Excerpt"],
    related: ["program_intelligence", "provenance", "evidence"],
    recommendedSection: "explore",
    sampleOutput: { title: "CPUC NEM 3.0 Decision", publisher: "CPUC", year: 2022 },
  },
  {
    id: "program_intelligence",
    title: "Program intelligence",
    what: "Live knowledge of rebates, tariffs, incentives (federal, state, utility) and their eligibility rules.",
    why: "The cost of any pathway depends on what you actually qualify for today.",
    who: "Planner estimates; Explore Learn cards; Builder hand-off pack.",
    homeownerQuestion: "What rebates and tariffs apply to me right now?",
    inputs: ["Home zip", "Utility", "Income bracket (optional)"],
    outputs: ["List of programs with deadlines and dollar amounts"],
    related: ["estimates", "source_documents"],
    recommendedSection: "explore",
    sampleOutput: { programs: 5, totalIncentiveUsd: 8400 },
  },
  {
    id: "twin_planning_context",
    title: "Planning context",
    what: "The narrative bridge between 'what is' (twin) and 'what could be' (planner) — what's possible next, and why.",
    why: "Without this, the jump from home view to pathway cards feels arbitrary.",
    who: "Explore narrative; Planner intro copy.",
    homeownerQuestion: "Given my house, what kind of upgrades even make sense?",
    inputs: ["Home id", "Goals"],
    outputs: ["Ordered list of viable directions with short rationales"],
    related: ["product_preferences", "scenarios", "design_advisor"],
    recommendedSection: "explore",
    sampleOutput: { directions: ["Solar + battery", "Heat pump first", "EV-ready panel"] },
  },

  // ─── Planner ─────────────────────────────────────────────────────────
  {
    id: "designs",
    title: "Design drafts",
    what: "Working drafts of a system design — components, sizing, placement notes — before they harden into a scenario.",
    why: "Planning is iterative; designs let an advisor or homeowner try variants without losing history.",
    who: "Planner power-users; future contractor co-edit.",
    homeownerQuestion: "Can I sketch a few options before committing to one?",
    inputs: ["Home id", "Component picks", "Notes"],
    outputs: ["Design id with versioned snapshots"],
    related: ["scenarios", "equipment", "takeoffs"],
    recommendedSection: "planner",
  },
  {
    id: "scenarios",
    title: "Scenarios",
    what: "The three (or N) pathway cards: Solar-first, Battery-first, Balanced — each a hardened plan with tradeoffs.",
    why: "Comparison is how homeowners decide. Scenarios make tradeoffs visible side-by-side.",
    who: "Homeowner; Planner; Builder once one is selected.",
    homeownerQuestion: "What are my realistic pathways, and what does each one give up?",
    inputs: ["Home id", "Goals", "Constraints (budget, timeline)"],
    outputs: ["Scenario list with cost, payback, resilience, carbon"],
    related: ["estimates", "design_advisor", "equipment"],
    recommendedSection: "planner",
    sampleOutput: { count: 3, recommendedId: "balanced" },
  },
  {
    id: "estimates",
    title: "Estimates",
    what: "Cost, payback, monthly bill delta and incentive math for each scenario.",
    why: "Homeowners decide in dollars and months, not kilowatts.",
    who: "Every pathway card; Builder hand-off; Explore rebate copy.",
    homeownerQuestion: "What will this cost me, and when do I break even?",
    inputs: ["Scenario id"],
    outputs: ["Upfront $", "Net after incentives", "Payback years", "Monthly bill change"],
    related: ["program_intelligence", "scenarios", "estimate_readiness"],
    recommendedSection: "planner",
    sampleOutput: { upfrontUsd: 32000, netUsd: 23600, paybackYears: 8.4 },
  },
  {
    id: "estimate_readiness",
    title: "Estimate readiness",
    what: "Tells the homeowner whether an estimate is rough, ranged, or contractor-ready — and what's missing if not.",
    why: "Hides the false precision problem: a number with no readiness signal looks like a quote.",
    who: "Every scenario card; Builder gate before share.",
    homeownerQuestion: "How much should I trust this number?",
    inputs: ["Scenario id"],
    outputs: ["Readiness tier (rough/ranged/ready)", "List of missing inputs"],
    related: ["estimates", "evidence", "system_visibility"],
    recommendedSection: "planner",
    sampleOutput: { tier: "ranged", missing: ["roof measurements", "utility 12-mo data"] },
  },
  {
    id: "equipment",
    title: "Equipment",
    what: "The concrete products picked for a scenario (this inverter, that battery, this heat pump).",
    why: "Turns an abstract pathway into something a contractor can quote.",
    who: "Planner chips on pathway cards; Builder bill of materials.",
    homeownerQuestion: "What hardware does this scenario actually use?",
    inputs: ["Scenario id"],
    outputs: ["Product list with quantities"],
    related: ["product_library", "takeoffs", "compatibility_rules"],
    recommendedSection: "planner",
  },
  {
    id: "compatibility_rules",
    title: "Compatibility rules",
    what: "The rule engine that says 'this inverter and that battery won't talk to each other' before money is spent.",
    why: "Most failed installs trace back to a compatibility miss; catching them in software is the highest-leverage check.",
    who: "Planner (live filtering); Explore (Learn explanation); Builder (final gate).",
    homeownerQuestion: "Do these pieces actually work together?",
    inputs: ["Equipment list"],
    outputs: ["Pass/fail per pair + rule citation"],
    related: ["equipment", "rule_provenance", "product_library"],
    recommendedSection: "planner",
    sampleOutput: { pairs: 6, failures: 1 },
  },
  {
    id: "design_advisor",
    title: "Design advisor",
    what: "Ranks the scenarios against the homeowner's goal weights and surfaces a 'Recommended' badge.",
    why: "Decision fatigue is real. A defensible default is more useful than three equal cards.",
    who: "Homeowner on Planner; Explore narrative copy.",
    homeownerQuestion: "If I had to pick one today, which makes the most sense?",
    inputs: ["Scenarios", "Goal weights"],
    outputs: ["Ranked scenario ids + rationale text"],
    related: ["product_preferences", "scenarios", "estimates"],
    recommendedSection: "planner",
    sampleOutput: { recommendedId: "balanced", rationale: "Balances payback and resilience for stated goals." },
  },
  {
    id: "proposal_option_sets",
    title: "Proposal option sets",
    what: "Pre-packaged ecosystem bundles (e.g. 'Tesla Powerwall 3 + 8kW') used in the Compare sidebar.",
    why: "Lets homeowners compare apples to apples across vendors without rebuilding a design each time.",
    who: "Planner Compare sidebar; Builder for share.",
    homeownerQuestion: "How does Tesla's bundle compare to Enphase's?",
    inputs: ["Home id", "Ecosystem filter"],
    outputs: ["Option set with components, cost band, lead time"],
    related: ["product_library", "scenarios", "crm_handoff"],
    recommendedSection: "planner",
  },
  {
    id: "takeoffs",
    title: "Takeoffs",
    what: "Bill of materials — wires, conduit, mounting, every SKU a contractor needs to quote.",
    why: "Turns a pathway into a quotable scope without manual re-entry.",
    who: "Builder; future contractor portal.",
    homeownerQuestion: "What is this contractor actually pricing line by line?",
    inputs: ["Scenario id", "Site constraints"],
    outputs: ["Line-itemed BOM with quantities"],
    related: ["equipment", "designs", "contractor_workflow"],
    recommendedSection: "builder",
  },
  {
    id: "planning",
    title: "Planning narrative",
    what: "The framing copy at the top of the Planner — what this stage is for and how to read it.",
    why: "Reduces 'what am I looking at' confusion when the homeowner lands cold.",
    who: "Planner page header; Explore handoff.",
    homeownerQuestion: "What am I supposed to do on this screen?",
    inputs: ["Home id", "Stage"],
    outputs: ["Heading + lede text"],
    related: ["twin_planning_context", "scenarios"],
    recommendedSection: "planner",
  },

  // ─── Builder ─────────────────────────────────────────────────────────
  {
    id: "contractor_workflow",
    title: "Contractor workflow",
    what: "The five lanes (Site visit → Design → Permit → Install → Commission) and what's blocking each.",
    why: "Once a contractor is engaged, the homeowner wants a shared view of progress, not a thread of emails.",
    who: "Homeowner and contractor; Planning exchange feeds it.",
    homeownerQuestion: "Where is my project right now, and what are we waiting on?",
    inputs: ["Project id"],
    outputs: ["Lane states with assignee + due date"],
    related: ["contractor_context", "planning_exchange", "crm_handoff"],
    recommendedSection: "builder",
    sampleOutput: { lanes: { siteVisit: "done", design: "in_progress", permit: "blocked" } },
  },
  {
    id: "contractor_context",
    title: "Contractor context",
    what: "Who the contractor is — company, license, primary contact, ecosystems they certify on.",
    why: "Provides the trust layer ('Bright Path Energy, C-46 license #...') around every workflow update.",
    who: "Homeowner reading the Builder header.",
    homeownerQuestion: "Who exactly am I working with on this?",
    inputs: ["Project id"],
    outputs: ["Company name", "License", "Contact", "Certifications"],
    related: ["contractor_workflow", "crm_handoff"],
    recommendedSection: "builder",
  },
  {
    id: "crm_handoff",
    title: "CRM hand-off",
    what: "Pushes a chosen scenario + scope into the contractor's CRM as a qualified lead.",
    why: "Avoids the homeowner having to re-explain their house and choices in a sales call.",
    who: "Planner Share button; contractor receiving the lead.",
    homeownerQuestion: "When I hit Share, what does my contractor actually see?",
    inputs: ["Scenario id", "Contractor id", "Privacy scope"],
    outputs: ["CRM lead id + share receipt"],
    related: ["privacy", "scenarios", "contractor_context"],
    recommendedSection: "builder",
  },
  {
    id: "planning_exchange",
    title: "Planning exchange",
    what: "The activity feed: comments, file drops, lane changes — the project conversation log.",
    why: "Single source of truth so the homeowner is not chasing emails or text threads.",
    who: "Homeowner; contractor team.",
    homeownerQuestion: "What's new on my project today?",
    inputs: ["Project id"],
    outputs: ["Time-ordered events with actor + attachment"],
    related: ["contractor_workflow", "contractor_context"],
    recommendedSection: "builder",
  },
  {
    id: "post_install",
    title: "Post-install",
    what: "After commissioning: as-built docs, monitoring set-up, warranty registration, performance baselines.",
    why: "Closes the loop — the twin should update from 'planned' to 'installed' and start verifying performance.",
    who: "Homeowner long-term; contractor for warranty.",
    homeownerQuestion: "Is everything that was installed actually performing as promised?",
    inputs: ["Project id", "Monitoring credentials"],
    outputs: ["As-built doc links", "Monitoring status", "Performance baseline"],
    related: ["contractor_workflow", "energy_passport", "system_visibility"],
    recommendedSection: "builder",
  },

  // ─── Internal ────────────────────────────────────────────────────────
  {
    id: "ai_context",
    title: "AI prompt grounding",
    what: "Builds the structured context blob the LLM receives for any homeowner-facing explanation.",
    why: "Keeps AI answers grounded in this home's facts, not generic web text.",
    who: "Every AI-narrated card (Explore, Inspector, Planner rationale).",
    homeownerQuestion: "Why does the assistant know things about my house?",
    inputs: ["Home id", "Surface id", "User question"],
    outputs: ["Context blob (facts, scenarios, citations) ready for the model"],
    related: ["facts", "provenance", "source_documents"],
    recommendedSection: "internal",
  },
  {
    id: "evidence",
    title: "Evidence",
    what: "Per-fact trust metadata: verified, derived, assumed, with source pointer.",
    why: "Powers the trust badges that distinguish a utility-bill kWh from a model-derived one.",
    who: "Inspector drawer; system visibility dots.",
    homeownerQuestion: "Is this number something you measured, or something you guessed?",
    inputs: ["Fact id"],
    outputs: ["Tier (verified/derived/assumed)", "Source pointer", "Last updated"],
    related: ["provenance", "facts", "system_visibility"],
    recommendedSection: "internal",
  },
  {
    id: "facts",
    title: "Facts substrate",
    what: "The normalized key/value store ('panel.amps = 100') that every other capability reads from.",
    why: "Without a single substrate, buildings/panels/loads drift out of sync.",
    who: "Internal — every router reads/writes here.",
    homeownerQuestion: "(Indirect — surfaces as Known Home Facts.)",
    inputs: ["Home id", "Fact key"],
    outputs: ["Value + provenance + evidence tier"],
    related: ["buildings", "evidence", "provenance"],
    recommendedSection: "internal",
  },
  {
    id: "geometry",
    title: "Roof & panel geometry",
    what: "Roof planes, azimuth, tilt, shading, and panel-layout polygons.",
    why: "Solar production estimates and physical install feasibility both need real geometry.",
    who: "Planner solar sizing; Builder for layout drawings.",
    homeownerQuestion: "Will solar actually fit and produce on my roof?",
    inputs: ["Home id"],
    outputs: ["Roof plane list", "Usable area", "Shading profile"],
    related: ["buildings", "scenarios", "equipment"],
    recommendedSection: "internal",
  },
  {
    id: "provenance",
    title: "Provenance",
    what: "For any value the system shows, where did it come from — homeowner entry, utility import, model, contractor doc.",
    why: "Auditability. Every number on the screen should be explainable.",
    who: "Inspector basis line; AI grounding; Builder review.",
    homeownerQuestion: "Where did you get this from?",
    inputs: ["Value id"],
    outputs: ["Origin label + timestamp + actor"],
    related: ["evidence", "source_documents", "ai_context"],
    recommendedSection: "internal",
  },
  {
    id: "rule_provenance",
    title: "Why this rule fired",
    what: "For each compatibility / readiness rule result, the exact rule text and which inputs triggered it.",
    why: "A red 'incompatible' badge is useless without the reason; this makes it teachable.",
    who: "Planner compatibility detail; Builder permit packets.",
    homeownerQuestion: "Why did the system flag this combination?",
    inputs: ["Rule fire id"],
    outputs: ["Rule text", "Input values that matched", "Citation"],
    related: ["compatibility_rules", "source_documents"],
    recommendedSection: "internal",
  },
  {
    id: "privacy",
    title: "Share scope & redaction",
    what: "Controls what a contractor or third party sees when a homeowner hits Share.",
    why: "Address, panel photos, and utility data are sensitive — sharing must be intentional and scoped.",
    who: "CRM hand-off; planning exchange attachments.",
    homeownerQuestion: "What exactly am I sharing, and with whom?",
    inputs: ["Scenario id", "Recipient id", "Scope toggles"],
    outputs: ["Redacted payload preview", "Share token"],
    related: ["crm_handoff", "accounts", "provenance"],
    recommendedSection: "internal",
  },
];

export type EnrichedCatalogEntry = CatalogEntry & {
  router: string;
  endpointGroup: string;
  status: CapabilityStatus;
  uiStatus: UiStatus;
};

export function enrichedCatalog(): EnrichedCatalogEntry[] {
  return CATALOG.map((e) => {
    const cap = CAPABILITIES.find((c) => c.id === e.id);
    return {
      ...e,
      router: cap?.router ?? e.id,
      endpointGroup: cap?.endpointGroup ?? `/${e.id}`,
      status: cap?.status ?? "backend_only",
      uiStatus: cap?.uiStatus ?? "missing",
    };
  });
}

export function catalogByGroup(group: CapabilityGroup): EnrichedCatalogEntry[] {
  return enrichedCatalog().filter((e) => e.recommendedSection === group);
}
