/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTwinRouteImport } from './routes/_app.twin'
import { Route as AppScenarioRouteImport } from './routes/_app.scenario'
import { Route as AppProgressRouteImport } from './routes/_app.progress'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppScenarioRoute = AppScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof AppProgressRoute
  '/scenario': typeof AppScenarioRoute
  '/twin': typeof AppTwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof AppProgressRoute
  '/scenario': typeof AppScenarioRoute
  '/twin': typeof AppTwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/progress': typeof AppProgressRoute
  '/_app/scenario': typeof AppScenarioRoute
  '/_app/twin': typeof AppTwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/progress' | '/scenario' | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/progress' | '/scenario' | '/twin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/progress'
    | '/_app/scenario'
    | '/_app/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/twin': {
      id: '/_app/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenario': {
      id: '/_app/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof AppScenarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProgressRoute: typeof AppProgressRoute
  AppScenarioRoute: typeof AppScenarioRoute
  AppTwinRoute: typeof AppTwinRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProgressRoute: AppProgressRoute,
  AppScenarioRoute: AppScenarioRoute,
  AppTwinRoute: AppTwinRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
