/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTwinRouteImport } from './routes/_app.twin'
import { Route as AppScenarioRouteImport } from './routes/_app.scenario'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppInternalRouteImport } from './routes/_app.internal'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppCatalogRouteImport } from './routes/_app.catalog'
import { Route as AppCapabilitiesRouteImport } from './routes/_app.capabilities'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppScenarioRoute = AppScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppInternalRoute = AppInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesRoute = AppCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof AppCapabilitiesRoute
  '/catalog': typeof AppCatalogRoute
  '/explore': typeof AppExploreRoute
  '/internal': typeof AppInternalRoute
  '/progress': typeof AppProgressRoute
  '/scenario': typeof AppScenarioRoute
  '/twin': typeof AppTwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof AppCapabilitiesRoute
  '/catalog': typeof AppCatalogRoute
  '/explore': typeof AppExploreRoute
  '/internal': typeof AppInternalRoute
  '/progress': typeof AppProgressRoute
  '/scenario': typeof AppScenarioRoute
  '/twin': typeof AppTwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/capabilities': typeof AppCapabilitiesRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/internal': typeof AppInternalRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/scenario': typeof AppScenarioRoute
  '/_app/twin': typeof AppTwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/catalog'
    | '/explore'
    | '/internal'
    | '/progress'
    | '/scenario'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/catalog'
    | '/explore'
    | '/internal'
    | '/progress'
    | '/scenario'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/capabilities'
    | '/_app/catalog'
    | '/_app/explore'
    | '/_app/internal'
    | '/_app/progress'
    | '/_app/scenario'
    | '/_app/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/twin': {
      id: '/_app/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenario': {
      id: '/_app/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof AppScenarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/internal': {
      id: '/_app/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof AppInternalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities': {
      id: '/_app/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof AppCapabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCapabilitiesRoute: typeof AppCapabilitiesRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppExploreRoute: typeof AppExploreRoute
  AppInternalRoute: typeof AppInternalRoute
  AppProgressRoute: typeof AppProgressRoute
  AppScenarioRoute: typeof AppScenarioRoute
  AppTwinRoute: typeof AppTwinRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCapabilitiesRoute: AppCapabilitiesRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppExploreRoute: AppExploreRoute,
  AppInternalRoute: AppInternalRoute,
  AppProgressRoute: AppProgressRoute,
  AppScenarioRoute: AppScenarioRoute,
  AppTwinRoute: AppTwinRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
